### ISSUE TITLE
大佬，帮我看一下这个问题？

### ISSUE THREAD

**Issue by wbdcyy** [yunwanjia-cloud/NavCreate#1]
F:\python\安装文件\python.exe F:/网页源码/NavCreate-master/main.py
Traceback (most recent call last):
  File "F:/网页源码/NavCreate-master/main.py", line 336, in <module>
    my = create_block(0, 1)
  File "F:/网页源码/NavCreate-master/main.py", line 290, in create_block
    now_line = f_text.readline()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x84 in position 184: illegal multibyte sequence

**Comment by Gyunist** [comment]
这应该是编码问题, 改一下编码格式就好了
